### PR TITLE
feat: [ref #58] support Pydantic v2

### PR DESCRIPTION
**Pull request by danielchalef**
Ref: #58 and https://github.com/langchain-ai/langchain/pull/8330

- Loosen project deps to allow pydantic>=1.10
- Attempt to import `pydantic.v1` (pydantic v2 compat), failing which import `pydantic` (i.e. pydantic v1)

### CODE REVIEW

**Comment by srhinos** [comment]
Btw I absolutely love this solution and didn’t even consider doing the soft v2 support before fully supporting v2-only as a follow up. 

Good job and hope this merges!

**Comment by Trinkes** [comment]
Any update on this PR?

**Comment by danielchalef** [comment]
@Trinkes We've made some major changes to the SDK recently and want to pause briefly before making further. Are you blocked on deploying Zep? If so, happy to discuss alternative approaches, including a pre-release.

**Comment by Trinkes** [comment]
hey @danielchalef, thank you for you quick response.
To be honest I want to bump the FastAPI version of my project but it depends on Langchain and Langchain depends on zep-python. 
I just wanted to bring more awareness of this and try to understand the ETA for this project to update to pydantic v2.

**Comment by ogabrielluiz** [comment]
Hey! I'm a maintainer of Langflow. Me and people all over the community have been wanting zep-python so bad hahah First, supabase had a version mismatch on httpx, now they bumped it but also bumped pydantic which makes it impossible to add zep again. Would love to add it. Let me know if there's something I can do to help with testing this release.

**Comment by danielchalef** [comment]
@ogabrielluiz I've released v1.1.0a1 with Pydantic v2 support via v1 compatibility. https://pypi.org/project/zep-python/1.1.0a0/

install using: 
``` 
pip install --pre zep-python
```

Let me know how it works out for you!

**Comment by ogabrielluiz** [comment]
@danielchalef Just tested it on my v2 branch and it works perfectly!

**Comment by danielchalef** [comment]
@ogabrielluiz Great. I'm going to add a few new features to 0.10.0 before pushing the release. Likely in a few days. 

Would love to chat further about what you're doing. Will drop you an email.

**Pull request merged**
